// Weekly Assignments content. This is the only file to edit each week.
//
// currentWeek: the week marked "This week" (0 = none yet).
// For each week:
//   date:      e.g. "Sept 30" (optional)
//   recap:     list of paragraphs, e.g. ["We started with...", "Next week..."]
//   files:     PDFs/handouts, e.g. { label: "Value study handout", href: "/assignment-files/pdfs/week-02-value-study.pdf" }
//   photos:    images, e.g. { src: "/assignment-files/photos/week-02-demo.jpg", caption: "Demo: value scale" }
//   materials: list of items to bring
// A week with no recap, files or photos shows as "Coming soon".
// Put uploaded PDFs in assignment-files/pdfs/ and images in assignment-files/photos/.

window.ASSIGNMENTS = {
  currentWeek: 0,
  weeks: [
    {
      week: 1,
      title: "Drawing Foundations I",
      topic: "See, simplify + construct",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Pencils HB–6B","eraser","sketchbook","a few household objects"],
    },
    {
      week: 2,
      title: "Drawing Foundations II",
      topic: "Light, value + composition",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Pencils","blending stump","desk lamp","a white object such as an egg or mug"],
    },
    {
      week: 3,
      title: "Drawing Foundations III",
      topic: "Transform: Surrealism",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Drawing kit and reference photos"],
    },
    {
      week: 4,
      title: "Color Theory + Egg Tempera",
      topic: "Mixing what you see",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Eggs","pigment pastes","palette","small brushes","watercolor paper or panel"],
    },
    {
      week: 5,
      title: "Pigment + Casein Paint",
      topic: "Paint is made",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Casein binder","pigment pastes","illustration board or cardboard","brushes"],
    },
    {
      week: 6,
      title: "Mixed Media I",
      topic: "Layer + transform",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Glue","scissors","collage papers","found materials","casein paints"],
    },
    {
      week: 7,
      title: "Mixed Media II",
      topic: "Composition",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Printed images","tracing paper","glue","paints"],
    },
    {
      week: 8,
      title: "Texture + Relief",
      topic: "When the surface becomes an object",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Cardboard","glue","string","modeling paste","plasticine"],
    },
    {
      week: 9,
      title: "Sculptural Materials I",
      topic: "Design + cast",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Plasticine","small container","pre-portioned plaster","mixing cup","gloves","goggles"],
    },
    {
      week: 10,
      title: "Sculptural Materials II",
      topic: "Carve + finish",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Carving tools","sandpaper","pigment wash","found materials"],
    },
    {
      week: 11,
      title: "Surface + Light",
      topic: "Gilding and reflection",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Gilding size","imitation leaf","soft brush","cast piece or panel"],
    },
    {
      week: 12,
      title: "Chance + Experimental Process",
      topic: "Chance and control",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Gel medium","brayer","gel plate","sun-print paper","laser-printed images"],
    },
    {
      week: 13,
      title: "Final Project I",
      topic: "Concept + material plan",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Anything from the semester’s kits; the student’s plan decides"],
    },
    {
      week: 14,
      title: "Final Project II",
      topic: "Build",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Final-project materials"],
    },
    {
      week: 15,
      title: "Final Project III",
      topic: "Develop + refine",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Final-project materials"],
    },
    {
      week: 16,
      title: "Final Project IV",
      topic: "Finish + present",
      date: "",
      recap: [],
      files: [],
      photos: [],
      materials: ["Finished work","a phone camera","good light"],
    },
  ],
};
